public with sharing class SimpleCollections1 
{
    public SimpleCollections1() 
    {

    }

    public Integer getMaxInList(List<Integer> values)
    {
        // change this method to return the largest number 
        // present in the list

        return null;
    }

    public Boolean isInList(List<Integer> values, Integer candidate)
    {
        // change this method to return true if the candidate value
        // is present in the list of values, otheerwise false

        return null;
    }

    public List<Integer> reverseList(List<Integer> values)
    {
        // change this method to return values list in reverse
        // order, e.g. if values is [1,2,3,4,4,6] then the
        // returned list will be [6,5,4,3,2,1]

        return null;
    }
    
    public List<Integer> shiftLeft(List<Integer> values, Integer num) 
    {
        // change this method to return values list shifted left 'num' 
        // times - e.g. if values is [1,2,3,4,5,6] and num is 2 then
        // the returned list will be [3,4,5,6,1,2]

        return null;
    }

    public List<Integer> joinAlternate(List<Integer> left, List<Integer> right) 
    {
        // change this method to join the supplied lists by alternating
        // left and right elements. E.g. if left is [2, 4, 6] and right is
        // [1,5,7] the returned list will be [2, 1, 4, 5, 6, 7]

        return null;
    }
}
